export const CLINIC_IDS = [
  'all-specialties',
  'internal-medicine',
  'cardiology',
  'neurology',
  'neurosurgery',
  'dermatology',
  'endocrinology',
  'gastroenterology',
  'pulmonology',
  'nephrology',
  'rheumatology',
  'hematology',
  'oncology',
  'infectious-disease',
  'allergy-immunology',
  'psychiatry',
  'obgyn',
  'urology',
  'ophthalmology',
  'ent',
  'orthopedics',
  'pmr',
  'pediatrics',
  'general-surgery',
  'cardiothoracic-vascular-surgery',
] as const;

export type ClinicId = (typeof CLINIC_IDS)[number];

export const CLINIC_LABELS: Record<ClinicId, string> = {
  'all-specialties': 'All Specialties',
  'internal-medicine': 'Internal Medicine',
  cardiology: 'Cardiology',
  neurology: 'Neurology',
  neurosurgery: 'Neurosurgery',
  dermatology: 'Dermatology',
  endocrinology: 'Endocrinology',
  gastroenterology: 'Gastroenterology',
  pulmonology: 'Pulmonology',
  nephrology: 'Nephrology',
  rheumatology: 'Rheumatology',
  hematology: 'Hematology',
  oncology: 'Oncology',
  'infectious-disease': 'Infectious Disease',
  'allergy-immunology': 'Allergy & Immunology',
  psychiatry: 'Psychiatry',
  obgyn: 'OB-GYN',
  urology: 'Urology',
  ophthalmology: 'Ophthalmology',
  ent: 'ENT',
  orthopedics: 'Orthopedics',
  pmr: 'PM&R',
  pediatrics: 'Pediatrics',
  'general-surgery': 'General Surgery',
  'cardiothoracic-vascular-surgery': 'Cardiothoracic & Vascular Surgery',
};
